/** A tiny ELIZA — the same trick Weizenbaum used in 1966: pattern-match the
 *  input, reflect the pronouns, and mirror it back. No understanding at all.
 *  This really runs; the "conversation" in Act 1 is generated by these rules. */

const REFLECT: Record<string, string> = {
  i: "you", me: "you", my: "your", mine: "yours", am: "are",
  "i'm": "you're", "i've": "you've", myself: "yourself",
  you: "I", your: "my", yours: "mine", "you're": "I'm",
};

function reflect(text: string): string {
  return text
    .trim()
    .replace(/[.?!]+$/, "")
    .split(/\s+/)
    .map((w) => REFLECT[w.toLowerCase()] ?? w)
    .join(" ");
}

const GREETINGS = ["hello", "hi", "hey", "good morning", "good evening"];

const CATCH_ALL = [
  "Please, go on.",
  "Tell me more about that.",
  "How does that make you feel?",
  "Why do you say that?",
  "I see. And what does that suggest to you?",
];

export function elizaReply(input: string, seed = 0): string {
  const text = input.toLowerCase().trim();

  if (GREETINGS.some((g) => text === g || text.startsWith(g + " "))) {
    return "Hello. How can I help you today?";
  }
  let m: RegExpMatchArray | null;
  if ((m = text.match(/\bi feel (.+)/))) {
    return `Why do you feel ${reflect(m[1])}?`;
  }
  if ((m = text.match(/\bi am (.+)/)) || (m = text.match(/\bi'm (.+)/))) {
    return `How long have you been ${reflect(m[1])}?`;
  }
  if ((m = text.match(/\bi (?:want|need) (.+)/))) {
    return `What would it mean to you if you got ${reflect(m[1])}?`;
  }
  if ((m = text.match(/\bmy (\w+)/))) {
    return `Tell me more about your ${m[1]}.`;
  }
  if ((m = text.match(/\bbecause (.+)/))) {
    return "Is that the real reason?";
  }
  if (text.includes("?")) {
    return "What do you think?";
  }
  return CATCH_ALL[seed % CATCH_ALL.length];
}

export interface Turn {
  who: "you" | "bot";
  text: string;
}

/** A scripted demo conversation — every bot line is produced by elizaReply,
 *  so nothing here is hand-written on the bot's side. */
export const DEMO_USER_LINES = [
  "Hello",
  "I feel nervous about my new job",
  "My manager keeps ignoring me",
  "I am not sure I belong here",
];

export function demoConversation(): Turn[] {
  const turns: Turn[] = [];
  DEMO_USER_LINES.forEach((line, i) => {
    turns.push({ who: "you", text: line });
    turns.push({ who: "bot", text: elizaReply(line, i) });
  });
  return turns;
}
